## Build
FROM golang:alpine AS build
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY *.go ./
RUN go build -o service

## Deploy
FROM alpine
WORKDIR /app
ENV SERVICE_PORT=8080
ENV PG_DB_URL=postgres://postgres:postgrespassword@host.docker.internal:5432/chinook_corp?sslmode=disable

COPY --from=build /app/service ./

EXPOSE 8080
ENTRYPOINT [ "/app/service" ]